### ISSUE TITLE
IWOMM risk

### ISSUE THREAD

**Issue by olmesm** [jhwohlgemuth/tomo-cli#95]
Neat tool, but why are you installing this globally?

Surely the better method would be to install tomo as a dev dependency alongside the other's once you've changed into the directory and done the first `npx tomo ...` command?

**Comment by jhwohlgemuth** [comment]
@olmesm 

I certainly understand where you are coming from, but I believe there is still room in modern times for global modules...even if simply as an option. Also, the `tomo add` functionality is meant to be used across projects in a sort of "global" manner.

In any case, I also like what you are saying. I will add the use-case to the README. Somthing like,
> Add `setup: "tomo new app --use-react --with-cesium"` script to your `package.json`

...I might have to make some code changes too.

I added this to the [tomo trello board](https://trello.com/b/keq2Bc4R/tomo-cli) and am going to close this issue.

Thanks!

**Comment by jhwohlgemuth** [comment]
Added with https://github.com/jhwohlgemuth/tomo-cli/commit/a59586cd94af3888ab420d05862ddbe6bf450dc8
